services:
  postgres:
    image: postgres:14
    container_name: pm-postgres
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: pm-redis
    ports:
      - '6379:6379'

  backend:
    build:
      context: ../backend-api
      dockerfile: Dockerfile
    image: pm-backend:latest
    container_name: pm-backend
    env_file:
      - ../backend-api/.env
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ../frontend-app
      dockerfile: Dockerfile
    image: pm-frontend:latest
    container_name: pm-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  pgdata: